### PR TITLE
[KT] Fix memory alignment

### PR DESCRIPTION
**Pull request by dmitriy-sobolev**
The current implementation does not respect the alignment requirements which results in UB. Here is a simplified code with what the current version does: [full link](https://godbolt.org/#z:OYLghAFBqd5QCxAYwPYBMCmBRdBLAF1QCcAaPECAMzwBtMA7AQwFtMQByARg9KtQYEAysib0QXACx8BBAKoBnTAAUAHpwAMvAFYTStJg1DIApACYAQuYukl9ZATwDKjdAGFUtAK4sGEgGykrgAyeAyYAHI%2BAEaYxBLSAA6oCoRODB7evgGkyamOAqHhUSyx8VK2mPYFDEIETMQEmT5%2BXIF2mA7pdQ0ERZExcQm29Y3N2W0jvf0lZQkAlLaoXsTI7BzmAMxhyN5YANQmm27ICgT4gkfYJhoAgls7e5iHx05nxJisVzf3ZtsMuy8ByObgIAE9EpgAPoEYhMQgKb53H5hAj7FjwhgQeY/EwAdisd32xP2XlSRn2TBhEOeRwAIvsFAgSAQjoTbiTSeTgPtotTIS8GehltF6GyfpzUZSoWgvIJBftNuKiSSpXzZfL6YrlfcVcSzugQCBUgAvaFoqmm2mbBlW1BUCBU8GQ%2Bb7ABU0o1rM27M5BqNVphvKhVoVdodfOdmFdHvVy0uPolJP9xrwZqDoa1lrTtMswatOqTxIAbqg8OgPXCAO4Ko2oSFwojEfbhKsQK04xN6xnnI1eVEADhhlaYVah0TBBEwCgVH1RcUSHwIMqYZxBKf7giHBDdVwg1c77KL0qjHstozRWrnggXS5Xa%2BOTppu822H3o/Hk%2Bnh%2BPkef%2BYvWdMHnYhF0wZdRAfNw/0hF832rT8pxnaxpQ7QtuxTWVL2OEFDjMMwn0hEAXjcJh0HQD4FAUEBizELxMG%2BABWNwGHMMwdU5fhiAgKU8AVDQ2X2PjcKpL1BOsaw8Bxbt8V9TkSSYLwiH2RJYQVc9ejwiwhI4%2BTiTdVTmy1PBdL0zDlmwtxcMMkjcLY4i2Ns453RskFcJTVxaFMw48VtXsUAspy3B7Q0QE89COWTfysKCvCzBg9gSLIijp2o2jvAY18TGY1j8O8riePlYSbX2ASfSEkjgzE8qJMsKTj1k49OUU5TXJKvkzk0lCTK7SK9IMtTjO8v1osCtznLaqznPsuLYoGoycOcjyGHQLzes5fE/NCmLxuC5bVoikbtrGxbgrYsQ8GABg2EEKF7ShYtHX5aMHPw2L238i6rpu5d7uLEFCMy7BXV2kKjXC9aouOpTYvO2hLuuxhfqoB6IAS%2BZXrMd6Uy%2BxHbr%2BkEEquEHTrBsKVrWo9uzrBsmCbfYsHoKd3yrH9kW7JcVgYUrC18n4OEWWhOEY3g/A4LRSFQTgrMsFCFGWVZc02HhSAITQBcWABrEBNjxAA6MxGIATkYswuA0DRGPNyRLf0ThJFF9XJc4XhqI0VX1cWOBYBgRAQAsxIlPISg0BYRI6DiCJWHWVQB38ABafxJH2YBkGQfYuDMA3eEwfAm3LPR%2BEEEQxHYCoi/kJQ1Cd3QuFIKs4USTgeEF4XHfF3gpY4AB5JTA7Re19ljhOk5TtOM82A39ggDww4joy/i4eZeDVjv5kWBBPiweJsTtjgHdIFgQH8Lg9aNjQB0NjQ8UkAc8QHZWzFIMWJa712QHd1etC932ICQUPw70DIBQCAAD54gGAFwTYT8sDFjwGsAAangTAVZu6QhfrwGgtApzEGomjJ20QwgNDBM3XghDmDEDBN3aI2hOirxVqHH63cGC0BIR3UgWBoheGAKRWgtBqLcF4FgDERhxDsPwB8LoxZpxO0wKoToSl1gS3nELdh8NohwkoR4LATtYR4CPoIxYVADDAAUEglBaDGCkJkMXUQ4hy6yEUCodQ7Da76EMMYWqNh1HUUgIsesNQBHxyoAoQwaQzT0lxj9fY8du6bE7tI4gxBywyL8ZUao6QXArXGK0IIK0ZiDHKLkFIaQBA5L0HkUpDACmlCGHXDoXQBA9DGJ4FoegGk1GaX0MIAxalFM6i0rIuSBndOKIUiQix5YrDWBMveItn5Oy7kPOOidk6p3TlAqeEBcCEBIHhZWy8PZry1iARi7tVEHyPmYSQBtGL%2BCNmYfwN9JCMTxMbG%2BCz2Fv1sB/I539SDez9rA%2BBmBg6gNQHPIBUc2CcGHqsseGys5mCEZgOBMyOA5zziQAudcK4l3sdICuTjq6uPaVUOhmSICuHKXXEIPTZh1OKfkdINKmVVJqXMep5LGm1AvKyjp3QLwcsZSM/lQr6XjKXqrD4wFDQaFbhweZGDnYcDpKikF%2BxzFVjiMskeazx6bKxtsrFC9lakH2LPQBOqthLxXp7BVlyJCTwfrffCZz/BJw0EbOuyrvluz%2BRrUg2t/BZxvhoSQ98jZG1vibE2e94mfNfi7AN6897IsTZ3ZNX9A2JNSM4SQQA%3D%3D%3D).

The proposed approach is to allocate some more memory (in case if padding is necessary) and place the data on the aligned addresses. Simplified code with what the fixed version does: [full link](https://godbolt.org/#z:OYLghAFBqd5QCxAYwPYBMCmBRdBLAF1QCcAaPECAMzwBtMA7AQwFtMQByARg9KtQYEAysib0QXACx8BBAKoBnTAAUAHpwAMvAFYTStJg1DIApACYAQuYukl9ZATwDKjdAGFUtAK4sGe1wAyeAyYAHI%2BAEaYxCAArBqkAA6oCoRODB7evnrJqY4CQSHhLFEx8baY9vkMQgRMxASZPn5cFVXptfUEhWGR0XEJCnUNTdmtQ109xaUDAJS2qF7EyOwc5gDMwcjeWADUJutuyEP4ggfYJhoAghtbO5j7h05DxJis55c3ZpsM2157BzcBAAnolMAB9AjEJiEBQfa63X73R5uNgsEjA%2BE3a7BAi7FgwhgQWafEwAdis1121N2XlSRl2TEhoIeBwAIrsFAgSAQDpSrjTafTgLsIsywY8OehFhF6HzPoLcYzwWgvIJJbt1vKqTSlWLVer2ZrtdiBTSTiAQKkAF4QvFMm2s9Ycx2oKgQJkgsGzXYAKmVBt5635gotVrwtsh1LFjo1rvdYq9mB9/v1izOwYV5oI6EtjqjnIjTo5DqL%2B0sovBseshdtbogiZZJMzCJ11IAbqg8Oh/dCAO4ay2oMHQojEXYhPsQR3NkPZ3MgLy4gAckN7TD74IiwIImAUGteuOiiVeBBVTCGgLDS8Eq4IvvOEH7s9JbeVSf9DuGeKNh8Ex9Pc9L0OT0WQfdZsCfDctx3PcX1bM0Oy7HtRQvCFEihA9MCPYgT0wM9RGAtxO27cDIK/Lp4MQzkczzIso1eAlgiwccjVjABaZVHRNQUSJQsQ8GAEJ0HBDDWOdGiFwEoTp1okBpIYNhBHBN1wXbQFGzBc5SErR0dIiNDRKhHTGMJFiqMFTTMFTKtvywnC8IIi8gzcKyyI9WhBOEoziCorNqTDVUf0OQFyzMUCwRAFEmHQdBXgUBQQHbMQvEwD5YjcBhzDMHiaX4YgICVPANQ0PldmK0KmUDMrrGsPASTfck50FakmC8IhdjEjUKIacsLHK3KWr9LqjTwQaWsCxZgrcUKRpCw4wqi7KUVC305pmhaw1cWhxvJF05KClbNrk7aTX8yTLUOwFQuyqylpA2L4sS5LvDSiCTAyrKzByltqPywr1QqiTSuDcqUUrarQdqyx6vOprzsFNqOrmjkYzsmsxt%2BobqTWzDRvG0MDqmo63E6vH5tJ7Klu%2BknhvJjbSa2hh0B2rGaT2i6UGJ67joXU7fvOyb2tp7KFKUs9VPbD1xWTamzFp2SpM8oTxZUqg1MBCK3uwH0ecZk7mdZ5rOauimwrFxgJfVqWrNmOWFbDC3lMljSZfOXWzaZlmzrfIcRyYMddiwehdygvs/LfU8lgYXYQf5PbPg4eZaE4WJeD8DgtFIVBOBmywawURZllZb4eFIAhNCT%2BYAGsQHWMkADozFiABOWIzC4DQNFiTvJG7/ROEkdPK%2BzzheEShIK8zpPSDgWAYEQEApsSdryEoNAWESOholCVhVlUZcADZ2MPyRdmAZBkF2LgzCb3hMHwMduz0fhBBEMR2CkGRBEUFR1Gn0guhWh9mhIkTgPBk6p2HgAnOHAADy7UV54jdLsA%2Bx9T7n0vtfdYTddgQA8JvberFS6zF4FPLQsx5gIDeCxSgkCOBD1ICwEAh8uANxbhoZczcNBkkkMuMky51g31IBnLOsDx4gEnpXeYc9F4by3vQMgFAIDyKISAYAXB1hmFIFgdseAVgADU8CYD7HAsEojeA0FoLuYgiUGwjwiMEeowJwG8EccwYgwI4ERG0JgBwrjSAb3FnAhgtAXEAKwBELwwA3BiFoIlbgvAsAEiMOICJeBXgODwO2PcI9MCqD8e1VYWcjwpwAZ5CI0JPEeCwCPKEeBmGJPmFQAwwAFBGJMWYxgATX7CFEOIL%2BvTf5qBHkA/QhhjDQxsBUxKkB5jDmqAk9iVAFCGDSLadkTs8TsTgesXgqAcnEGIN2XJcy2h%2BOqC4ZmowWikECMEXoJR%2BitFyGkAQNycgpDeQwKYfQYjjEqBcjo34PkAvaAIToDRflPP%2BbYEFnhmh6AmFCh50xnnzELksFYEh6FpxESPWBqCj4nzPhfK%2BmjcEQFwIQEg5YhGkPLtImuAwB4MN4Mwswkgm6xEPi3Mwh9eGSFiGSVuvD8UwLHrYSRjLp4yIXhAJAuj9GYDXio1AhDFG7zYJwNBJLMHktvmYJJmA9HYo4PfR%2BJBn6tF6e/AZ0ghlKBGQAsZdggXOAgK4UFdzmbQpmC8r51RvWvOqH6555yskQvhVkW5brI01G/GG2FyLGgIrGHCyYqK/k4vLq8bCuYNC4ugWIzgbITXKt2B0vs0QiXoNJVgil8sqWWuIUInSBCFE1o2FwBl5Cq6ssYcwilgi%2BHfXiIfU%2BGgW6tAsaPc1UqpGyuZYfW%2BvCNCSAES3FufC25t1ZXs8VJb519soayo1h79mSpPfMQ5qRnCSCAA).

### CODE REVIEW

**Comment by dmitriy-sobolev** [comment]
All tests have passed

**Comment by SergeyKopienko** [comment]
@dmitriy-sobolev let's discuss offline?

**Comment by dmitriy-sobolev** [comment]
> @dmitriy-sobolev let's discuss offline?

It's been discussed with the conclusion:

- Add `noexcept` where applicable
- Handle a case when the memory allocation has failed

**Review by SergeyKopienko — APPROVED** [review]
LGTM

**Pull request merged**
